spring.application.name=salvamento

# Configuração do RabbitMQ
spring.rabbitmq.host=jackal-01.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=slaymxly
spring.rabbitmq.password=mTYka5EhvF6rTO4UXN9cRNaJj3vcBxmW
spring.rabbitmq.virtual-host=slaymxly

# Para aplicações console (não web)
spring.main.web-application-type=none

# Configurações de logging para debug
logging.level.org.springframework.amqp=INFO
logging.level.com.furb.folha=DEBUG

# Configurações do RabbitMQ para melhor desempenho
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3