spring.application.name=salvamento

# Configuração do RabbitMQ
spring.rabbitmq.host=jackal.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=slaymxly:slaymxly
spring.rabbitmq.password=mTYka5EhvF6rTO4UXN9cRNaJj3vcBxmW
spring.rabbitmq.virtual-host=slaymxly